//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace preprova2
{
    using System;
    using System.Collections.Generic;
    
    public partial class aluno
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public int id_turma { get; set; }
        public bool ativo { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
    }
}
